sonar.projectKey=devops-end-to-end
sonar.projectName=DevOps End to End Project
sonar.sourceEncoding=UTF-8

sonar.sources=app/backend
sonar.tests=app/backend/_test_

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**
