pipeline {
    agent any

    tools {
        nodejs 'node18'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'develop',
                    url: 'https://github.com/chetanbairagioffice83222-a11y/devops-end-to-end-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'cd app/backend && npm ci'
            }
        }

        stage('Syntax Check') {
            steps {
                sh 'cd app/backend && node --check index.js'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'cd app/backend && npm test'
            }
        }

        stage('SonarQube Analysis') {
            environment {
                SCANNER_HOME = tool 'SonarScanner'
            }
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh """
                        ${SCANNER_HOME}/bin/sonar-scanner
                    """
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline Successful'
        }
        failure {
            echo '❌ Pipeline Failed'
        }
    }
}
